name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pytest
        run: |
          pip install pytest

      - name: Run tests
        run: pytest
        
      - name: Run tests and save results
        run: |
          mkdir -p test-results
          pytest --junitxml=test-results/results.xml

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: test-results/results.xml

      - name: Publish test results to GitHub
          uses: actions/upload-test-results@v2
          with:
            files: test-results/results.xml

      - name: Deploy to Production (simulated)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "🚀 Starting deployment..."
          echo "Code successfully deployed at $(date)"
      
      - name: Mirror to deenoc/test
        if: github.repository == 'deenoo2/test' && github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "deenoc"
          git config --global user.email "deenoo.g@gmail.com"
          git clone --bare https://github.com/deenoo2/test.git mirror-repo
          cd mirror-repo
          git push --mirror https://deenoc:${{ secrets.FORK_PUSH_TOKEN }}@github.com/deenoc/test.git

      - name: Run tests with coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=verify --cov-report=xml
      
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          
          

          
